### ISSUE TITLE
[PE-D][Tester C] Example given in UG about add command is not valid!

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-3/tp#123]
### There are typos about the add command in UG Quick Start
May consider to change to "/e johnd@example.com", and "/a" instead of "a/"

![image.png](https://raw.githubusercontent.com/Propene-Dan/ped/main/files/2dfc61d4-6106-4be8-bcb0-2eac6eba3ac9.png)

### In addition, there are also typos about the same command in features part

![image.png](https://raw.githubusercontent.com/Propene-Dan/ped/main/files/ce060786-f1ff-4738-ac93-0bff663e2cf7.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: Propene-Dan/ped#3

**Comment by simbayippy** [comment]
fix the a/
