### ISSUE TITLE
[PE-D][Tester A] Add person bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W09-3/tp#129]
I am unable to add a person even after adding the specified command parameters. Also, hard to undertsand where i'm going wrong because of no error message to display what the issue is. 
![Screenshot 2023-11-03 at 4.23.58 PM.png](https://raw.githubusercontent.com/D-Limiter/ped/main/files/280081b9-4899-40f9-981e-88c6513cda72.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: D-Limiter/ped#1

**Comment by yezkez10** [comment]
solved by wenjia
