### ISSUE TITLE
[PE-D][Tester A] edit command suggestion message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-3/tp#133]
it would be nice to get som sort of message showing i got the index wrong
![Screenshot 2023-11-03 at 4.30.47 PM.png](https://raw.githubusercontent.com/D-Limiter/ped/main/files/0460e838-8796-4814-8c75-a2a4da43593e.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: D-Limiter/ped#2

**Comment by simbayippy** [comment]
this is not a index error but an invalid command error. user put n/ but accepted format is /n
