### ISSUE TITLE
[PE-D][Tester B] Edit appointment on not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-3/tp#153]
When I tried to edit the first appointment `edit_appt 1 /on 05-02-2024 12:00`, I got errors:
edit_appt 2 /on 05-02-2024 12:00

I notice that the error message is based on the previous error message. For example, suppose I try to edit appointment 2 when I only have 1 appointment, I would get index out of bound error, but when I try to edit appointment 1 (which now has a valid index), I would get the same error.  
When I key in other commands and got a different error, and now tries to edit appointment 1 again, I got the previous error. Not sure what causes this error.

**After trying to edit 2**

![image.png](https://raw.githubusercontent.com/JCSnap/ped/main/files/93ccc623-b58d-458b-95b6-dcbbbfd3b02d.png)

**After keying an invalid command**

![image.png](https://raw.githubusercontent.com/JCSnap/ped/main/files/1c9ba6b5-3c1c-4155-a95d-eb28264bbaab.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: JCSnap/ped#10

**Comment by simbayippy** [comment]
wtf is this

**Comment by JCSnap** [comment]
were you able to reproduce it? @simbayippy

**Comment by simbayippy** [comment]
omg LOL did not know u could see this @JCSnap
