### ISSUE TITLE
[PE-D][Tester E] Bug for `view` function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-3/tp#155]
![CleanShot 2023-11-03 at 17.00.00@2x.png](https://raw.githubusercontent.com/ruth-lim/ped/main/files/b6aa62a5-0cad-40d7-a802-21f90463b863.png)

The timeslot list does not display all available timeslots that can be booked **on the DATE** only.
The list keeps adding on when new `view` queries are entered.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ruth-lim/ped#12

**Comment by wj331** [comment]
![image](https://github.com/AY2324S1-CS2103T-W09-3/tp/assets/122218312/fca43a8a-32c5-44d5-a645-50db131d9e9d)

Fixed in PR #111 with resetTimeslot function
