### ISSUE TITLE
FIXED [PE-D][Tester D] `appt` command given in UG is not able to run

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W09-3/tp#156]
The UG states that the only required fields for the `appt` command are the `/for`, `/d`, and `/on` fields.

![image.png](https://raw.githubusercontent.com/elhy1999/ped/main/files/c611d1b0-1b4d-419e-855d-c1909a4a0df0.png)

However, running the commands below seems to produce an error:
```
add_doctor /n Dr Lee /p 12345678 /e leemed@nus.edu.sg /age 45 /a Clementi Blk 987 #14-022 /g M
appt /for 1 /d knee injury /on 02-01-2024 12:00
```

This is what the application looks like after running the commands above:

![image.png](https://raw.githubusercontent.com/elhy1999/ped/main/files/b34fd3b4-2736-4ca4-8b1c-f99493a65078.png)

Hmmm... Should there be a `/doc` field specified as well? :/

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: elhy1999/ped#7

**Comment by simbayippy** [comment]
just need to update UG to contain doctor field too
