### ISSUE TITLE
Add New Patients

### ISSUE THREAD

**Issue by wj331** [AY2324S1-CS2103T-W09-3/tp#9]
As a clinic assistant, I can register new patients to the clinic's database so that I can reduce the use of physical documents and storage costs.

**Comment by yezkez10** [comment]
Adds a new appointment to a specific patient at index. Need to include the upcoming date of this new appointment.

Format: add appt /for INDEX /on DATE
Note: 
An appointment must have all tags to work. e.g. add appt, add appt /for 3, add appt /on 2023-09-17 will not work

Examples:
Valid input: add appt /for 6 /on 2023-09-17 13:00
This adds a new appointment to patient at index 6.
Output (success): Appointment added for Drizzy on 17th September, 1pm
Invalid input: add appt /for 6 /on today
Output (failure): Could not add appointment: Date given must be in yyyy-mm-dd HH:mm format!
Invalid input: add appt /for 6
Output (failure): Could not add appointment: Missing appointment details
